"""Add floor, area, and sub_area tables

Revision ID: 2025_11_01_0001
Revises: 
Create Date: 2025-11-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2025_11_01_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('icon', sa.String(length=255), nullable=True),
        sa.Column('aliases', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('areas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('floor_id', sa.Integer(), nullable=True),
        sa.Column('icon', sa.String(length=255), nullable=True),
        sa.Column('label', sa.String(length=255), nullable=True),
        sa.Column('image', sa.Text(), nullable=True),
        sa.Column('aliases', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('sub_areas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('area_id', sa.Integer(), nullable=False),
        sa.Column('icon', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_areas')
    op.drop_table('areas')
    op.drop_table('floors')
    # ### end Alembic commands ###