"""Add Home Assistant

Revision ID: 21f744080608
Revises: a5c220713937
Create Date: 2025-10-21 20:02:50.853105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '21f744080608'
down_revision: Union[str, None] = 'a5c220713937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_data',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.BigInteger(), nullable=True),
    sa.Column('shared_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_table('event_types',
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('event_type_id')
    )
    op.create_table('migration_changes',
    sa.Column('migration_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('migration_id')
    )
    op.create_table('recorder_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('closed_incorrect', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('schema_changes',
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('changed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_table('state_attributes',
    sa.Column('attributes_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.BigInteger(), nullable=True),
    sa.Column('shared_attrs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('attributes_id')
    )
    op.create_table('states_meta',
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    op.create_table('statistics_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statistic_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('unit_of_measurement', sa.String(length=255), nullable=True),
    sa.Column('has_mean', sa.Boolean(), nullable=True),
    sa.Column('has_sum', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mean_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('origin_idx', sa.SmallInteger(), nullable=True),
    sa.Column('time_fired', sa.DateTime(), nullable=True),
    sa.Column('time_fired_ts', sa.Float(), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('context_user_id', sa.String(length=36), nullable=True),
    sa.Column('context_parent_id', sa.String(length=36), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('context_id_bin', sa.Text(), nullable=True),
    sa.Column('context_user_id_bin', sa.Text(), nullable=True),
    sa.Column('context_parent_id_bin', sa.Text(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['event_data.data_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.event_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.SmallInteger(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('last_changed_ts', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_updated_ts', sa.Float(), nullable=True),
    sa.Column('old_state_id', sa.Integer(), nullable=True),
    sa.Column('attributes_id', sa.Integer(), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('context_user_id', sa.String(length=36), nullable=True),
    sa.Column('context_parent_id', sa.String(length=36), nullable=True),
    sa.Column('origin_idx', sa.SmallInteger(), nullable=True),
    sa.Column('context_id_bin', sa.Text(), nullable=True),
    sa.Column('context_user_id_bin', sa.Text(), nullable=True),
    sa.Column('context_parent_id_bin', sa.Text(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.Column('last_reported_ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attributes_id'], ['state_attributes.attributes_id'], ),
    sa.ForeignKeyConstraint(['metadata_id'], ['states_meta.metadata_id'], ),
    sa.ForeignKeyConstraint(['old_state_id'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Float(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('start_ts', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('last_reset_ts', sa.Float(), nullable=True),
    sa.Column('state', sa.Float(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('mean_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['statistics_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics_short_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Float(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('start_ts', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('last_reset_ts', sa.Float(), nullable=True),
    sa.Column('state', sa.Float(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('mean_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['statistics_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('model_id', table_name='model')
    op.drop_table('model')
    op.drop_index('idx_oauth_session_expires_at', table_name='oauth_session')
    op.drop_index('idx_oauth_session_user_id', table_name='oauth_session')
    op.drop_index('idx_oauth_session_user_provider', table_name='oauth_session')
    op.drop_table('oauth_session')
    op.drop_table('channel_member')
    op.drop_table('channel')
    op.drop_table('message')
    op.drop_table('note')
    op.drop_table('feedback')
    op.drop_table('knowledge')
    op.drop_index('prompt_command', table_name='prompt')
    op.drop_table('prompt')
    op.drop_index('tool_id', table_name='tool')
    op.drop_table('tool')
    op.drop_index('memory_id', table_name='memory')
    op.drop_table('memory')
    op.drop_index('function_id', table_name='function')
    op.drop_index('is_global_idx', table_name='function')
    op.drop_table('function')
    op.drop_index('document_collection_name', table_name='document')
    op.drop_index('document_name', table_name='document')
    op.drop_table('document')
    op.drop_table('migratehistory')
    op.drop_table('config')
    op.drop_table('message_reaction')
    op.drop_index('chatidtag_id', table_name='chatidtag')
    op.drop_table('chatidtag')
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('auth', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.drop_index('auth_id', table_name='auth')
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('chat', 'share_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('chat', 'archived',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_index('chat_id', table_name='chat')
    op.drop_index('chat_share_id', table_name='chat')
    op.create_unique_constraint(None, 'chat', ['share_id'])
    op.alter_column('file', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index('file_id', table_name='file')
    op.alter_column('folder', 'user_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('folder', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('folder', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('folder', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('folder', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('user_id_idx', table_name='tag')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.drop_index('user_api_key', table_name='user')
    op.drop_index('user_id', table_name='user')
    op.drop_index('user_oauth_sub', table_name='user')
    op.create_unique_constraint(None, 'user', ['api_key'])
    op.create_unique_constraint(None, 'user', ['oauth_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('user_oauth_sub', 'user', ['oauth_sub'], unique=1)
    op.create_index('user_id', 'user', ['id'], unique=1)
    op.create_index('user_api_key', 'user', ['api_key'], unique=1)
    op.alter_column('user', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'last_active_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'profile_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('user_id_idx', 'tag', ['user_id'], unique=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('folder', 'updated_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('folder', 'created_at',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('folder', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('folder', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('folder', 'user_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index('file_id', 'file', ['id'], unique=1)
    op.alter_column('file', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('file', 'filename',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('file', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat', type_='unique')
    op.create_index('chat_share_id', 'chat', ['share_id'], unique=1)
    op.create_index('chat_id', 'chat', ['id'], unique=1)
    op.alter_column('chat', 'meta',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('chat', 'archived',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat', 'share_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('chat', 'updated_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'created_at',
               existing_type=sa.BigInteger(),
               type_=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('auth_id', 'auth', ['id'], unique=1)
    op.alter_column('auth', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('auth', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('chatidtag',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False)
    )
    op.create_index('chatidtag_id', 'chatidtag', ['id'], unique=1)
    op.create_table('message_reaction',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('message_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migratehistory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('migrated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('filename', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_name', 'document', ['name'], unique=1)
    op.create_index('document_collection_name', 'document', ['collection_name'], unique=1)
    op.create_table('function',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('valves', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('is_global', sa.INTEGER(), nullable=False)
    )
    op.create_index('is_global_idx', 'function', ['is_global'], unique=False)
    op.create_index('function_id', 'function', ['id'], unique=1)
    op.create_table('memory',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False)
    )
    op.create_index('memory_id', 'memory', ['id'], unique=1)
    op.create_table('tool',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('specs', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('valves', sa.TEXT(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True)
    )
    op.create_index('tool_id', 'tool', ['id'], unique=1)
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('command', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('prompt_command', 'prompt', ['command'], unique=1)
    op.create_table('knowledge',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('version', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('snapshot', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('channel_id', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('parent_id', sa.TEXT(), nullable=True),
    sa.Column('reply_to_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('channel_member',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('channel_id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('oauth_session',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('provider', sa.TEXT(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_session_user_provider', 'oauth_session', ['user_id', 'provider'], unique=False)
    op.create_index('idx_oauth_session_user_id', 'oauth_session', ['user_id'], unique=False)
    op.create_index('idx_oauth_session_expires_at', 'oauth_session', ['expires_at'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('base_model_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=False),
    sa.Column('params', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('access_control', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False)
    )
    op.create_index('model_id', 'model', ['id'], unique=1)
    op.drop_table('statistics_short_term')
    op.drop_table('statistics')
    op.drop_table('states')
    op.drop_table('events')
    op.drop_table('statistics_runs')
    op.drop_table('statistics_meta')
    op.drop_table('states_meta')
    op.drop_table('state_attributes')
    op.drop_table('schema_changes')
    op.drop_table('recorder_runs')
    op.drop_table('migration_changes')
    op.drop_table('event_types')
    op.drop_table('event_data')
    # ### end Alembic commands ###
