"""add_floor_area_subarea_tables

Revision ID: eccf02c21de2
Revises: d31026856c01
Create Date: 2025-11-01 18:28:26.310443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.internal.db
from backend.migrations.util import get_existing_tables

# revision identifiers, used by Alembic.
revision: str = 'eccf02c21de2'
down_revision: Union[str, None] = 'd31026856c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    existing_tables = set(get_existing_tables())
    
    # ### commands auto generated by Alembic - please adjust! ###
    if "floors" not in existing_tables:
        op.create_table('floors',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('level', sa.Integer(), nullable=True),
            sa.Column('icon', sa.String(length=255), nullable=True),
            sa.Column('aliases', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    
    if "areas" not in existing_tables:
        op.create_table('areas',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('floor_id', sa.Integer(), nullable=True),
            sa.Column('icon', sa.String(length=255), nullable=True),
            sa.Column('label', sa.String(length=255), nullable=True),
            sa.Column('image', sa.Text(), nullable=True),
            sa.Column('aliases', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    if "sub_areas" not in existing_tables:
        op.create_table('sub_areas',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('area_id', sa.Integer(), nullable=False),
            sa.Column('icon', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_areas')
    op.drop_table('areas')
    op.drop_table('floors')
    # ### end Alembic commands ###